projet_a/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('website/', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('categorie/', views.categorie, name='images'),
    path('images/<slug:slug>/', views.images, name='images'),
    path('presentation/', views.presentation, name='presentation'),
]

migrate/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

# Create your models here.

migrate/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader, context
from django.template.loader import get_template


def index(request):
    return render(request, 'website/index.html')


def images(request, slug):
    return render(request, 'website/images.html', {"post": slug})


def presentation(request):
    return render(request, 'website/presentation.html')


def categorie(request):
    return render(request, 'website/categorie.html')

website/templates/website/categorie.html
{% include 'website/header.html' %}

<section class="backgroundI">
    <h1>Catégories</h1>
    <h2>Les photos</h2>
</section>
<section class="bibliCat">
    <h2>Nom</h2>
    <ul class="catList">
        <li>
            <a href="/website/images/elephant/">Éléphant</a>

            <p>8 Photos</p>
        </li>
        <li><a href="/website/images/test/">Test</a><p>8 Photos</p></li>
        <li><a href="/website/images/lorem/">Lorem</a><p>8 Photos</p></li>
    </ul>
</section>
{% include 'website/footer.html' %}

website/templates/website/footer.html
{% load static %}

<section class="footer">
    <ul>
        <li><h2>Information</h2></li>
        <li class="footerInfo"><a href="#">Question & Réponses</a></li>
        <li class="footerInfo"><a href="#">Me contacter</a></li>
    </ul>
    <ul>
        <li ><h2>Légal</h2></li>
        <li class="footerInfo"><a href="#">Mentions Légales</a></li>
    </ul>
    <ul>
        <li><h2>Me suivre</h2></li>
        <li class="social">
            <img src="{% static "website/img/logo-instagram.png" %}">
            <img src="{% static "website/img/twitter.png" %}">
        </li>
    </ul>
</section>

website/templates/website/header.html
{% load static %}
{# CSS #}
<link rel="stylesheet" type="text/css" href="{% static 'website/css/reset.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'website/css/main.css' %}">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

{# JS #}
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js"></script>
<script src="{% static "website/js/main.js" %}"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<div class="nav">

    {#          Burger  #}
    <div class="toggle">
        <div class="bar"></div>
    </div>

    {#          Menu  #}
    <nav class="hidden">
        <div class="showcase">
            <div class="showcase-container">
                <ul class="showcase-menu">
                    <li>Hi!</li>
                    <li>Hover over the list items or click them!</li>
                    <li class="overlay"
                        style="background-image:url(https://images.unsplash.com/photo-1537949721120-e8f21f6698e6?ixlib=rb-0.3.5&s=96527c5eff0b3bd24946f77f4dc5a789&auto=format&fit=crop&w=634&q=80);">
                        Lorem ipsum
                    </li>
                </ul>
            </div>
        </div>

        <div class="menu">
            <ul class="main-menu">
                <li class="active"><a href="{% url 'website:index' %}">Accueil</a></li>
                <li><a href="{% url 'website:images' %}">Images</a></li>
                <li><a href="{% url 'website:presentation' %}">Présentation</a></li>
            </ul>
        </div>
    </nav>
</div>

website/templates/website/images.html
{% include 'website/header.html' %}

<section class="backgroundI">
    <h1>{{ post }}</h1>
    <h2>Photos</h2>
</section>
<section class="bandeauImages">
    <div data-aos="fade-right" data-aos-duration="1500" class="tags">
        <ul>
            <li>Test</li>
            <li>Test2</li>
            <li>Test3</li>
        </ul>
    </div>
    <div data-aos="zoom-in-left" data-aos-duration="1500" class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio</div>
</section>
<section class="bibliImages">
    <div class="wrapper">
        <img src="https://source.unsplash.com/random/600x600?water" alt="">
        <img src="https://source.unsplash.com/random/600x600?summer" alt="">
        <img src="https://source.unsplash.com/random/600x600?plants" alt="">
        <img src="https://source.unsplash.com/random/600x600?snow" alt="">
        <img src="https://source.unsplash.com/random/600x600?roses" alt="">
        <img src="https://source.unsplash.com/random/600x600?sky" alt="">
        <img src="https://source.unsplash.com/random/600x600?nature" alt="">
        <img src="https://source.unsplash.com/random/600x600?blossom" alt="">
        <img src="https://source.unsplash.com/random/600x600?ice" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
        <img src="https://source.unsplash.com/random/600x600?spring" alt="">
    </div>
</section>
<script>
    AOS.init();
</script>
{% include 'website/footer.html' %}

website/templates/website/index.html
{% include 'website/header.html' %}

<div id="container" class="container">
    {#  Slider  #}
    <section class="background">
        <div class="content-wrapper">
            <p class="content-title">Be Present</p>
            <section class="portfolio-experiment">
                <a href="/website/images/elephant/">
                    <span class="text">Pour voir plus d'éléphant</span>
                    <span class="line -right"></span>
                    <span class="line -top"></span>
                    <span class="line -left"></span>
                    <span class="line -bottom"></span>
                </a>
            </section>
        </div>
    </section>
    <section class="background">
        <div class="content-wrapper">
            <p class="content-title">Be All There</p>
            <section class="portfolio-experiment">
                <a href="/website/images/test/">
                    <span class="text">Pour voir plus de ...</span>
                    <span class="line -right"></span>
                    <span class="line -top"></span>
                    <span class="line -left"></span>
                    <span class="line -bottom"></span>
                </a>
            </section>
        </div>
    </section>
    <section class="background">
        <div class="content-wrapper">
            <p class="content-title">Be Here</p>
            <section class="portfolio-experiment">
                <a href="/website/images/lorem/">
                    <span class="text">Pour voir plus de lorem</span>
                    <span class="line -right"></span>
                    <span class="line -top"></span>
                    <span class="line -left"></span>
                    <span class="line -bottom"></span>
                </a>
            </section>
        </div>
    </section>
</div>

website/templates/website/presentation.html
{% include 'website/header.html' %}
<section class="backgroundI">
    <h1>Qui suis-je ?</h1>
    <h2>Marc Dupond</h2>
</section>
<section class="bandeauImages profil">
    <div data-aos="fade-right" data-aos-duration="1500" class="tags">
        <img src="https://source.unsplash.com/random/600x600?water" alt="">
    </div>
    <div data-aos="zoom-in-left" data-aos-duration="1500" class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio</div>
</section>
<section class="bibliImages">

</section>
<script>
    AOS.init();
</script>
{% include 'website/footer.html' %}